### ISSUE TITLE
[PE-D][Tester A] Names are only alphanumeric

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T12-3/tp#109]
In the context of hiring, it may be important to have the full name of the employee. However, since names are only accepted to be alphanumeric, it does not allow the following common name types 

- hyphens (eg. rui-en)
- slashes (eg. s/o)
- capitalisation is automatic for the first letter

Additionally, if i want to abbreviate names with a period, i can't do it :(

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: 4llysa/ped#5

**Comment by ChuaZenKhoon** [comment]
fixed.
