### ISSUE TITLE
[PE-D][Tester D] Functionality missing: budgeting and salary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-3/tp#113]
![Screenshot 2024-04-05 at 4.37.59 PM.jpg](https://raw.githubusercontent.com/NeoHW/ped/main/files/9718f812-19a7-402b-9b87-5dacef511ad1.jpg)

![Screenshot 2024-04-05 at 4.38.13 PM.jpg](https://raw.githubusercontent.com/NeoHW/ped/main/files/f063c8a5-b476-454a-9b29-7e29adccc02c.jpg)

In the product information welcome note: there is a mentioned on "Constrained by company **budgeting** and unable to appeal for a HR application?"

However, there is no implementation or usage for budgeting or salary in the application

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: NeoHW/ped#7

**Comment by shunjieee** [comment]
What's wrong with this dude

**Comment by shunjieee** [comment]
Man doesn't know the difference between target audience and proposed functionality

**Comment by shunjieee** [comment]
It is as hard as asking him to differentiate his mum and dad

**Comment by ChuaZenKhoon** [comment]
fixed.
