### ISSUE TITLE
[PE-D][Tester C] PDF version of the user guide has some sections grayed out and hard to read 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-3/tp#116]
![image.png](https://raw.githubusercontent.com/E0735389/ped/main/files/d9c4de65-75c5-454e-9f2c-48608bf722c2.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: E0735389/ped#4

**Comment by ChuaZenKhoon** [comment]
fixed.
