### ISSUE TITLE
[PE-D][Tester C] Unusual ordering of menu items

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-3/tp#118]
![image.png](https://raw.githubusercontent.com/E0735389/ped/main/files/5a2a12a1-c4e5-41a2-b67c-86197f3d62fd.png)

In almost all normal Windows application, the menu bar is organized File → Edit → View → ⋯ → Help. Having Help as the 2nd option is disorienting to the viewer.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: E0735389/ped#5

**Comment by ChuaZenKhoon** [comment]
not allowed to fix.
