### ISSUE TITLE
[PE-D][Tester E] Toggle Command: Missing Purpose

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-3/tp#158]
Hi, this is a small issue and I'm sure you have a reason for this command. I think it would be good for you to include it in the UG for clarity purposes as now the usage is not really clear. It can help potential users maximize the functionality of the product too!

Other than that, the feature is working as intended, good job!

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ziyang27/ped#13

**Comment by ShanylOng** [comment]
Fixed issue - included a portion in the UG describing the benefits of having a toggle display function.
