### ISSUE TITLE
[PE-D][Tester B] Add function does not work

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T12-3/tp#93]
+ /name John Doe /id johndoe41 /hp 98765432

shows

Invalid command format! 
+: Adds a person to the address book.
Parameters: /name NAME /id ID /hp PHONE /tag TAG
Example: + /name John Doe /id johndoe41 /hp 98765432 /tag Finance

At first thought my inputs were wrong, but even using your example does not work

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Cedricaca/ped#2

**Comment by shunjieee** [comment]
Sohai bro, forget add `+` blame until his mother see no tmr
