### ISSUE TITLE
[PE-D][Tester E] User Guide: Suggestion for links

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T12-3/tp#99]
This is not a bug.

Under the Quick Start Section, point 6, maybe you can look into adding a link to the register command. As it took quite some time for me to scroll down to find it.

If you are unable to do that, perhaps you can look into recording the commands and put the register command at the start instead.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: ziyang27/ped#2

**Comment by ChuaZenKhoon** [comment]
fixed.
